### ISSUE TITLE
Shophistic-Lite/js/script.js -> Difficulties with dependent select

### ISSUE THREAD

**Issue by Nexotap** [nicoandrade/Shophistic-Lite#1]
Hi
I encountered a problem while having 2 product variations. I can choose the first selection (Lets's say color) once and then it stops working.

I havent much clue of how this all is clued together but i think, the problem must be somewhere here:
Shophistic-Lite/js/script.js

Maybe I'm doing something wrong or is it really a bug?

**Comment by nicoandrade** [comment]
Hi Nexotap,
Yes, this issue is solved in the latest version (1.0.6)
Thanks for sharing.
