### ISSUE TITLE
Can't access cart on mobile devices (<768 px) via default cart button

### ISSUE THREAD

**Issue by dontbyte** [nicoandrade/Shophistic-Lite#2]
Hi there, 

the chevron-down is hidden on mobile devices. Therefor it's not possible to access the cart on mobile devices by clicking the default cart button on the upper right. Is there any possiblity to change this behaviour? So that it's possible to open the cart by clicking the button (ql_cart-btn).

Thanks!

**Comment by dontbyte** [comment]
@nicoandrade 
It's working on shophistic but not on shophistic-lite theme. Any ideas?

**Comment by nicoandrade** [comment]
This was fixed in the new 1.0.13 version.
Thanks.
