### ISSUE TITLE
Sidebar menu to the top of the page

### ISSUE THREAD

**Issue by dontbyte** [nicoandrade/Shophistic-Lite#3]
On mobile phones the sidebar menu appears at the bottom after all the shop content. 
Is it possible to place the sidebar menu on the top?

Thanks in advance!

**Comment by nicoandrade** [comment]
Hi there,
In that case you should change the order for the sidebar and the prodcuts.
The sidebar is called in 
https://github.com/nicoandrade/Shophistic-Lite/blob/fd264937a1e72440eae8923b7e6db9f1d210759d/templates/afterloop-woocommerce.php#L11

You should place it before the products in shophistic-lite/templates/beforeloop-woocommerce.php

Also make a few changes to the CSS.
