### ISSUE TITLE
Show product size in cart

### ISSUE THREAD

**Issue by dontbyte** [nicoandrade/Shophistic-Lite#4]
Is it possible to also show the product size in the cart? 
What do I need to change?

Thanks in advance and thanks for your great work!

**Comment by nicoandrade** [comment]
Hi,
Right now the size of your product is showing on both carts:
![captura_de_pantalla_2018-09-26_a_las_10_59_04_a_m_](https://user-images.githubusercontent.com/1398677/46084965-41919c00-c17b-11e8-9d58-7c6a8947f12f.png)
![cart_ _shophistic_lite](https://user-images.githubusercontent.com/1398677/46084971-448c8c80-c17b-11e8-948a-becc42f78199.png)

**Comment by dontbyte** [comment]
Okay, that's odd. I can't see the product size in Shophistic nor in Shophistic-Lite. 

Shophistic 
![27-09-2018 07-45-55](https://user-images.githubusercontent.com/25500244/46125486-94299180-c229-11e8-8dd1-e4aa0dff62f6.png)

Shophistic-Lite
![27-09-2018 07-46-07](https://user-images.githubusercontent.com/25500244/46125490-97248200-c229-11e8-9df4-a3ee30507e97.png)

Is there any option I don't see?

**Comment by dontbyte** [comment]
I've endet up overriding the woocommerce/cart/cart.php. So this issue can be closed.

Keep up with your good work - I really like your themes!
