### ISSUE TITLE
[Bug] jQuery Slidemenu won't work anymore when login/cart is in different row than logo/navbar

### ISSUE THREAD

**Issue by dontbyte** [nicoandrade/Shophistic-Lite#5]
Site: http://demo.quemalabs.com/shophistic-lite/

As soon as the _login_cart_wrap_ is not in the same row as the _ql_logo_nav_ the jQuery Slidemenu won't work anymore. It's only possible to move over the first 2 or 3 menu items, but when moving the cursor over an item below then the menu closes immediately.

![image](https://user-images.githubusercontent.com/25500244/46270139-30afa480-c546-11e8-90e3-790a54106e21.png)

**Comment by dontbyte** [comment]
Maybe it's enough to change the z-index of _.ql_logo_nav_ from 30 to 50 so that it's higher than the z-index of 30 of  the _.login_cart_wrap_?

**Comment by nicoandrade** [comment]
Thank you! Added on next update
